# Generated by Django 5.0.6 on 2024-07-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/256/1516/1516233.png', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=True),
        ),
    ]
