# Generated by Django 5.0.6 on 2024-07-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_image_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=False, max_digits=5),
        ),
    ]
